import type {
    Alert,
    Recommendation,
    Corridor,
    SystemHealth,
    AuditAction,
    PredictiveSnapshot,
} from '@/types';

// ── Alerts ────────────────────────────────
export const MOCK_ALERTS: Alert[] = [
    {
        id: 'alert-001',
        type: 'congestion',
        severity: 'critical',
        severityLevel: 4,
        status: 'active',
        title: 'Severe gridlock — CBD Ring Road',
        description: 'Stationary traffic spanning 2.4km. Multiple signal failures detected.',
        location: { lat: -1.2921, lng: 36.8219, label: 'CBD Ring Road / Haile Selassie Ave', zone: 'CBD', corridorId: 'corridor-001' },
        detectedAt: new Date(Date.now() - 12 * 60 * 1000),
        updatedAt: new Date(Date.now() - 2 * 60 * 1000),
        confidence: 97,
        confidenceMetadata: {
            dataCompleteness: 96,
            lastTrainingUpdate: new Date(Date.now() - 4 * 60 * 60 * 1000),
            modelVersion: 'v3.2.1',
        },
        impact: { metric: 'Congestion Index', value: 94, unit: '%' },
        timer: { expiresAt: new Date(Date.now() + 8 * 60 * 1000), urgency: 'critical' },
        affectedIntersections: ['int-001', 'int-002', 'int-003'],
        affectedAgencies: ['traffic', 'emergency'],
        agency: 'traffic',
        suggestedAction: 'Activate alternate corridor via Moi Avenue',
    },
    {
        id: 'alert-002',
        type: 'incident',
        severity: 'critical',
        severityLevel: 5,
        status: 'active',
        title: 'Multi-vehicle collision — Thika Road',
        description: '3-vehicle accident blocking 2 lanes. Ambulance dispatched.',
        location: { lat: -1.2631, lng: 36.8350, label: 'Thika Rd / Garden City Junction', zone: 'North', corridorId: 'corridor-004' },
        detectedAt: new Date(Date.now() - 8 * 60 * 1000),
        updatedAt: new Date(Date.now() - 1 * 60 * 1000),
        confidence: 99,
        confidenceMetadata: {
            dataCompleteness: 100,
            lastTrainingUpdate: new Date(Date.now() - 4 * 60 * 60 * 1000),
            modelVersion: 'v3.2.1',
        },
        impact: { metric: 'Lanes blocked', value: 2, unit: ' lanes' },
        timer: { expiresAt: new Date(Date.now() + 4 * 60 * 1000), urgency: 'critical' },
        affectedIntersections: ['int-010', 'int-011'],
        affectedAgencies: ['traffic', 'emergency', 'transport'],
        agency: 'emergency',
        suggestedAction: 'Dispatch traffic police. Activate bypass via Outer Ring.',
    },
    {
        id: 'alert-003',
        type: 'congestion',
        severity: 'high',
        severityLevel: 3,
        status: 'active',
        title: 'Heavy congestion — Uhuru Highway',
        description: 'Peak hour buildup. 45min above normal travel times.',
        location: { lat: -1.2990, lng: 36.8163, label: 'Uhuru Hwy / University Way', zone: 'CBD', corridorId: 'corridor-002' },
        detectedAt: new Date(Date.now() - 25 * 60 * 1000),
        updatedAt: new Date(Date.now() - 5 * 60 * 1000),
        confidence: 88,
        confidenceMetadata: {
            dataCompleteness: 84,
            lastTrainingUpdate: new Date(Date.now() - 4 * 60 * 60 * 1000),
            modelVersion: 'v3.2.1',
        },
        impact: { metric: 'Delay', value: 45, unit: ' min' },
        affectedIntersections: ['int-004', 'int-005'],
        affectedAgencies: ['traffic'],
        agency: 'traffic',
        suggestedAction: 'Extend green phase on southbound signals by 15s',
    },
    {
        id: 'alert-004',
        type: 'signal_failure',
        severity: 'high',
        severityLevel: 3,
        status: 'active',
        title: 'Signal failure — Westlands roundabout',
        description: 'Traffic light controller offline. Manual direction needed.',
        location: { lat: -1.2671, lng: 36.8104, label: 'Westlands Roundabout', zone: 'Westlands' },
        detectedAt: new Date(Date.now() - 18 * 60 * 1000),
        updatedAt: new Date(Date.now() - 3 * 60 * 1000),
        confidence: 100,
        confidenceMetadata: {
            dataCompleteness: 100,
            lastTrainingUpdate: new Date(Date.now() - 4 * 60 * 60 * 1000),
            modelVersion: 'v3.2.1',
        },
        impact: { metric: 'Queue length', value: 800, unit: 'm' },
        timer: { expiresAt: new Date(Date.now() + 12 * 60 * 1000), urgency: 'normal' },
        affectedIntersections: ['int-020'],
        affectedAgencies: ['traffic'],
        agency: 'traffic',
        suggestedAction: 'Dispatch traffic marshal. Enable adaptive override.',
    },
    {
        id: 'alert-005',
        type: 'congestion',
        severity: 'medium',
        severityLevel: 2,
        status: 'active',
        title: 'Moderate slowdown — Ngong Road',
        description: 'Construction zone reducing to single lane. 20min delays.',
        location: { lat: -1.3010, lng: 36.7840, label: 'Ngong Rd / Prestige Plaza', zone: 'South', corridorId: 'corridor-003' },
        detectedAt: new Date(Date.now() - 40 * 60 * 1000),
        updatedAt: new Date(Date.now() - 10 * 60 * 1000),
        confidence: 63,
        confidenceMetadata: {
            dataCompleteness: 61,
            lastTrainingUpdate: new Date(Date.now() - 8 * 60 * 60 * 1000),
            modelVersion: 'v3.1.0',
        },
        impact: { metric: 'Delay', value: 20, unit: ' min' },
        affectedIntersections: ['int-015'],
        affectedAgencies: ['traffic'],
        agency: 'traffic',
        suggestedAction: 'Monitor. Update VMS signage.',
    },
    {
        id: 'alert-006',
        type: 'congestion',
        severity: 'medium',
        severityLevel: 2,
        status: 'active',
        title: 'Slow traffic — Lang\'ata Road',
        description: 'Approaching school hours. Expect buildup near Karen junction.',
        location: { lat: -1.3180, lng: 36.7630, label: 'Lang\'ata Rd / Karen Roundabout', zone: 'South' },
        detectedAt: new Date(Date.now() - 22 * 60 * 1000),
        updatedAt: new Date(Date.now() - 5 * 60 * 1000),
        confidence: 71,
        confidenceMetadata: {
            dataCompleteness: 78,
            lastTrainingUpdate: new Date(Date.now() - 4 * 60 * 60 * 1000),
            modelVersion: 'v3.2.1',
        },
        impact: { metric: 'Avg speed', value: 12, unit: ' kph' },
        affectedIntersections: ['int-031'],
        affectedAgencies: ['traffic'],
        agency: 'traffic',
        suggestedAction: 'Monitor. School zone signals active.',
    },
    {
        id: 'alert-007',
        type: 'weather',
        severity: 'medium',
        severityLevel: 2,
        status: 'active',
        title: 'Heavy rain reducing visibility',
        description: 'Rainfall reducing road grip. 15% increased incident probability.',
        location: { lat: -1.2800, lng: 36.8200, label: 'City-wide', zone: 'All' },
        detectedAt: new Date(Date.now() - 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 15 * 60 * 1000),
        confidence: 93,
        confidenceMetadata: {
            dataCompleteness: 90,
            lastTrainingUpdate: new Date(Date.now() - 2 * 60 * 60 * 1000),
            modelVersion: 'v3.2.1',
        },
        impact: { metric: 'Incident risk', value: 15, unit: '% ↑' },
        affectedIntersections: [],
        affectedAgencies: ['traffic', 'emergency'],
        agency: 'traffic',
        suggestedAction: 'Reduce signal cycle speeds. Alert VMS for reduced speed.',
    },
    {
        id: 'alert-008',
        type: 'camera_offline',
        severity: 'low',
        severityLevel: 1,
        status: 'active',
        title: 'Camera offline — Mombasa Rd',
        description: 'CCTV unit #MR-04 offline. No visual coverage of southern approach.',
        location: { lat: -1.3200, lng: 36.8400, label: 'Mombasa Rd / SGR Bridge', zone: 'South' },
        detectedAt: new Date(Date.now() - 90 * 60 * 1000),
        updatedAt: new Date(Date.now() - 90 * 60 * 1000),
        confidence: 100,
        affectedIntersections: [],
        agency: 'traffic',
        suggestedAction: 'Schedule maintenance. Route nearest mobile unit.',
    },
    {
        id: 'alert-009',
        type: 'sensor_offline',
        severity: 'low',
        severityLevel: 1,
        status: 'active',
        title: 'Sensor offline — Outer Ring Road',
        description: 'Loop detector at OR-7 unresponsive. Fallback to camera estimates.',
        location: { lat: -1.2900, lng: 36.8550, label: 'Outer Ring Rd / Donholm Junction', zone: 'East' },
        detectedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
        confidence: 100,
        affectedIntersections: [],
        agency: 'traffic',
        suggestedAction: 'Log for maintenance. No immediate action needed.',
    },
    {
        id: 'alert-010',
        type: 'event',
        severity: 'info',
        severityLevel: 1,
        status: 'acknowledged',
        title: 'Kasarani Stadium event — 18:00',
        description: 'Match day. 40,000 expected. Plan road management from 16:00.',
        location: { lat: -1.2210, lng: 36.8960, label: 'Kasarani Stadium', zone: 'Northeast' },
        detectedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 60 * 60 * 1000),
        confidence: 100,
        affectedIntersections: [],
        affectedAgencies: ['traffic', 'transport'],
        agency: 'transport',
        suggestedAction: 'Pre-activate corridor plan K-3. Alert matatu operators.',
    },
];

// ── Recommendations ───────────────────────
export const MOCK_RECOMMENDATIONS: Recommendation[] = [
    {
        id: 'rec-001',
        title: 'Green wave — Moi Avenue northbound',
        description: 'Coordinate signals at 7 intersections to create uninterrupted green wave, reducing CBD-to-Westlands travel time.',
        confidence: 91,
        status: 'pending',
        interventionType: 'signal_timing',
        affectedCorridors: ['corridor-001', 'corridor-002'],
        expectedImpact: {
            congestionReduction: 23,
            fuelSavingsLiters: 340,
            travelTimeSavedMinutes: 11,
        },
        generatedAt: new Date(Date.now() - 5 * 60 * 1000),
        expiresAt: new Date(Date.now() + 25 * 60 * 1000),
    },
    {
        id: 'rec-002',
        title: 'Activate emergency corridor — Thika Rd bypass',
        description: 'Open contraflow on Outer Ring Road to divert traffic from incident site. Estimated 18% throughput improvement.',
        confidence: 85,
        status: 'pending',
        interventionType: 'corridor_activation',
        affectedCorridors: ['corridor-004', 'corridor-005'],
        expectedImpact: {
            congestionReduction: 18,
            travelTimeSavedMinutes: 24,
        },
        generatedAt: new Date(Date.now() - 3 * 60 * 1000),
        expiresAt: new Date(Date.now() + 30 * 60 * 1000),
    },
    {
        id: 'rec-003',
        title: 'Deploy traffic marshals — Westlands',
        description: 'Signal failure requires 2 officers at Westlands roundabout. Available units at Parklands base.',
        confidence: 99,
        status: 'pending',
        interventionType: 'dispatch',
        affectedCorridors: [],
        expectedImpact: {
            congestionReduction: 15,
            travelTimeSavedMinutes: 8,
        },
        generatedAt: new Date(Date.now() - 8 * 60 * 1000),
        expiresAt: new Date(Date.now() + 15 * 60 * 1000),
    },
];

// ── Corridors ─────────────────────────────
export const MOCK_CORRIDORS: Corridor[] = [
    {
        id: 'corridor-001',
        name: 'CBD Ring Road',
        status: 'blocked',
        flowRate: 120,
        capacityRate: 1800,
        avgSpeedKph: 4,
        cameras: [],
        intersections: ['int-001', 'int-002', 'int-003'],
    },
    {
        id: 'corridor-002',
        name: 'Uhuru Highway',
        status: 'congested',
        flowRate: 680,
        capacityRate: 2200,
        avgSpeedKph: 18,
        cameras: [],
        intersections: ['int-004', 'int-005'],
    },
    {
        id: 'corridor-003',
        name: 'Ngong Road',
        status: 'congested',
        flowRate: 820,
        capacityRate: 1600,
        avgSpeedKph: 22,
        cameras: [],
        intersections: ['int-015'],
    },
    {
        id: 'corridor-004',
        name: 'Thika Superhighway',
        status: 'emergency',
        flowRate: 200,
        capacityRate: 3000,
        avgSpeedKph: 8,
        cameras: [],
        intersections: ['int-010', 'int-011'],
    },
    {
        id: 'corridor-005',
        name: 'Mombasa Road',
        status: 'normal',
        flowRate: 1100,
        capacityRate: 2800,
        avgSpeedKph: 65,
        cameras: [],
        intersections: [],
    },
];

// ── System Health ─────────────────────────
export const MOCK_SYSTEM_HEALTH: SystemHealth = {
    iotNetworkPercent: 94,
    aiConfidence: 82,
    uptimePercent: 99.8,
    activeOperators: 3,
    dataDelaySeconds: 0,
    lastRefreshedAt: new Date(),
};

// ── Recent Actions ────────────────────────
export const MOCK_ACTIONS: AuditAction[] = [
    {
        id: 'action-001',
        type: 'alert_approved',
        performedBy: 'Amina Osei',
        agency: 'traffic',
        timestamp: new Date(Date.now() - 3 * 60 * 1000),
        targetId: 'alert-005',
        targetLabel: 'Moderate slowdown — Ngong Road',
    },
    {
        id: 'action-002',
        type: 'dispatch_sent',
        performedBy: 'David Kimani',
        agency: 'emergency',
        timestamp: new Date(Date.now() - 7 * 60 * 1000),
        targetId: 'alert-002',
        targetLabel: 'Ambulance to Thika Road collision',
    },
    {
        id: 'action-003',
        type: 'signal_adjusted',
        performedBy: 'Amina Osei',
        agency: 'traffic',
        timestamp: new Date(Date.now() - 14 * 60 * 1000),
        targetId: 'corridor-002',
        targetLabel: 'Uhuru Hwy — +15s green phase',
    },
    {
        id: 'action-004',
        type: 'ai_rejected',
        performedBy: 'Fatima Nkosi',
        agency: 'traffic',
        timestamp: new Date(Date.now() - 22 * 60 * 1000),
        targetId: 'rec-old-01',
        targetLabel: 'Contraflow suggestion — Langata Rd',
        details: { reason: 'Construction vehicles active in that zone until 20:00' },
    },
];

// ── Predictive snapshots ──────────────────
export const MOCK_PREDICTIVE: PredictiveSnapshot[] = [
    {
        slot: 'now',
        hotspots: [
            { corridorId: 'corridor-001', severity: 'critical' },
            { corridorId: 'corridor-004', severity: 'critical' },
            { corridorId: 'corridor-002', severity: 'high' },
        ],
        parkingDemand: 'high',
        ptDelayRisk: 'high',
        weatherImpact: 'minor',
        eventImpact: undefined,
    },
    {
        slot: '+30',
        hotspots: [
            { corridorId: 'corridor-001', severity: 'high' },
            { corridorId: 'corridor-002', severity: 'medium' },
        ],
        parkingDemand: 'moderate',
        ptDelayRisk: 'moderate',
        weatherImpact: 'none',
    },
    {
        slot: '+60',
        hotspots: [
            { corridorId: 'corridor-002', severity: 'medium' },
            { corridorId: 'corridor-005', severity: 'low' },
        ],
        parkingDemand: 'moderate',
        ptDelayRisk: 'low',
        weatherImpact: 'none',
        eventImpact: 'Kasarani match crowd dispersal beginning',
    },
    {
        slot: '+120',
        hotspots: [
            { corridorId: 'corridor-005', severity: 'high' },
        ],
        parkingDemand: 'low',
        ptDelayRisk: 'moderate',
        weatherImpact: 'none',
        eventImpact: 'Post-match Kasarani — heavy outbound on Thika Rd',
    },
];

// ── Historical traffic snapshots (past 6h at 1h intervals) ───────────────
export interface HistoricalSnapshot {
    hoursAgo:   number;   // 0 = now, 1 = 1h ago, etc.
    label:      string;
    corridors: {
        corridorId: string;
        flowRate:   number;   // vehicles/hour
        avgSpeedKph: number;
        status: 'normal' | 'slow' | 'congested' | 'blocked' | 'emergency';
    }[];
    incidentCount: number;
    avgNetworkSpeed: number; // kph city-wide
}

export const MOCK_HISTORICAL: HistoricalSnapshot[] = [
    {
        hoursAgo: 5, label: '5h ago',
        avgNetworkSpeed: 38, incidentCount: 1,
        corridors: [
            { corridorId: 'corridor-001', flowRate: 1200, avgSpeedKph: 32, status: 'normal' },
            { corridorId: 'corridor-002', flowRate: 1400, avgSpeedKph: 40, status: 'normal' },
            { corridorId: 'corridor-003', flowRate: 900,  avgSpeedKph: 35, status: 'normal' },
            { corridorId: 'corridor-004', flowRate: 1600, avgSpeedKph: 80, status: 'normal' },
            { corridorId: 'corridor-005', flowRate: 1100, avgSpeedKph: 62, status: 'normal' },
        ],
    },
    {
        hoursAgo: 4, label: '4h ago',
        avgNetworkSpeed: 32, incidentCount: 1,
        corridors: [
            { corridorId: 'corridor-001', flowRate: 1500, avgSpeedKph: 22, status: 'slow' },
            { corridorId: 'corridor-002', flowRate: 1700, avgSpeedKph: 28, status: 'slow' },
            { corridorId: 'corridor-003', flowRate: 1100, avgSpeedKph: 28, status: 'normal' },
            { corridorId: 'corridor-004', flowRate: 1800, avgSpeedKph: 72, status: 'normal' },
            { corridorId: 'corridor-005', flowRate: 1300, avgSpeedKph: 55, status: 'normal' },
        ],
    },
    {
        hoursAgo: 3, label: '3h ago',
        avgNetworkSpeed: 19, incidentCount: 3,
        corridors: [
            { corridorId: 'corridor-001', flowRate: 1750, avgSpeedKph: 10, status: 'congested' },
            { corridorId: 'corridor-002', flowRate: 1900, avgSpeedKph: 12, status: 'congested' },
            { corridorId: 'corridor-003', flowRate: 1400, avgSpeedKph: 18, status: 'slow' },
            { corridorId: 'corridor-004', flowRate: 1950, avgSpeedKph: 58, status: 'normal' },
            { corridorId: 'corridor-005', flowRate: 1500, avgSpeedKph: 48, status: 'normal' },
        ],
    },
    {
        hoursAgo: 2, label: '2h ago',
        avgNetworkSpeed: 11, incidentCount: 5,
        corridors: [
            { corridorId: 'corridor-001', flowRate: 300,  avgSpeedKph: 4,  status: 'blocked' },
            { corridorId: 'corridor-002', flowRate: 650,  avgSpeedKph: 10, status: 'congested' },
            { corridorId: 'corridor-003', flowRate: 1200, avgSpeedKph: 14, status: 'slow' },
            { corridorId: 'corridor-004', flowRate: 0,    avgSpeedKph: 8,  status: 'emergency' },
            { corridorId: 'corridor-005', flowRate: 1400, avgSpeedKph: 40, status: 'normal' },
        ],
    },
    {
        hoursAgo: 1, label: '1h ago',
        avgNetworkSpeed: 9, incidentCount: 6,
        corridors: [
            { corridorId: 'corridor-001', flowRate: 180,  avgSpeedKph: 4,  status: 'blocked' },
            { corridorId: 'corridor-002', flowRate: 680,  avgSpeedKph: 15, status: 'congested' },
            { corridorId: 'corridor-003', flowRate: 1100, avgSpeedKph: 16, status: 'slow' },
            { corridorId: 'corridor-004', flowRate: 0,    avgSpeedKph: 6,  status: 'emergency' },
            { corridorId: 'corridor-005', flowRate: 1350, avgSpeedKph: 38, status: 'normal' },
        ],
    },
    {
        hoursAgo: 0, label: 'Now',
        avgNetworkSpeed: 8, incidentCount: 7,
        corridors: [
            { corridorId: 'corridor-001', flowRate: 120,  avgSpeedKph: 4,  status: 'blocked' },
            { corridorId: 'corridor-002', flowRate: 680,  avgSpeedKph: 18, status: 'congested' },
            { corridorId: 'corridor-003', flowRate: 950,  avgSpeedKph: 14, status: 'congested' },
            { corridorId: 'corridor-004', flowRate: 0,    avgSpeedKph: 8,  status: 'emergency' },
            { corridorId: 'corridor-005', flowRate: 1300, avgSpeedKph: 42, status: 'normal' },
        ],
    },
];